//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationWebSiteMvc.Services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Base", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.ActivityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.Activity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.AssociatedActivityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.DispatchPriority))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.FileAssociation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.OnHoldReason))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.CommentAuditRecord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.Material))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.ReferenceType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.ScheduleDetails))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.SchedulingPriority))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.SkillsMatrix))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.ResourceProfile))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.Skill))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.ActivityTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.PerformanceIndicator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.PerformanceMeasurement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.TaskUpdateType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.ActivityTaskTemplate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.ActivityTaskAssociation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.TaskLookupData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.PriorityLookupData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BusinessObjects.WorkManagement.ActivityTree))]
    public partial class Base : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AssociatedActivityReferenceCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="AssociatedActivityReference")]
    [System.SerializableAttribute()]
    public class AssociatedActivityReferenceCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.AssociatedActivityReference> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FileAssociationCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="FileAssociation")]
    [System.SerializableAttribute()]
    public class FileAssociationCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.FileAssociation> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OnHoldReasonCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="OnHoldReason")]
    [System.SerializableAttribute()]
    public class OnHoldReasonCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.OnHoldReason> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CommentAuditRecordCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="CommentAuditRecord")]
    [System.SerializableAttribute()]
    public class CommentAuditRecordCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.CommentAuditRecord> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MaterialCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="Material")]
    [System.SerializableAttribute()]
    public class MaterialCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.Material> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReferenceTypeCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="ReferenceType")]
    [System.SerializableAttribute()]
    public class ReferenceTypeCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.ReferenceType> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ScheduleDetailsCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="ScheduleDetails")]
    [System.SerializableAttribute()]
    public class ScheduleDetailsCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.ScheduleDetails> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ResourceProfileCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="ResourceProfile")]
    [System.SerializableAttribute()]
    public class ResourceProfileCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.ResourceProfile> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SkillCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="Skill")]
    [System.SerializableAttribute()]
    public class SkillCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.Skill> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ActivityTaskCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="ActivityTask")]
    [System.SerializableAttribute()]
    public class ActivityTaskCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.ActivityTask> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PerformanceMeasurementCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="PerformanceMeasurement")]
    [System.SerializableAttribute()]
    public class PerformanceMeasurementCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.PerformanceMeasurement> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ActivityTaskAssociationCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="ActivityTaskAssociation")]
    [System.SerializableAttribute()]
    public class ActivityTaskAssociationCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.ActivityTaskAssociation> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TaskUpdateTypeCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="TaskUpdateType")]
    [System.SerializableAttribute()]
    public class TaskUpdateTypeCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.TaskUpdateType> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DispatchPriorityCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="DispatchPriority")]
    [System.SerializableAttribute()]
    public class DispatchPriorityCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.DispatchPriority> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SchedulingPriorityCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="SchedulingPriority")]
    [System.SerializableAttribute()]
    public class SchedulingPriorityCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.SchedulingPriority> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ActivityCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="Activity")]
    [System.SerializableAttribute()]
    public class ActivityCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.Activity> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ActivityTaskTemplateCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="ActivityTaskTemplate")]
    [System.SerializableAttribute()]
    public class ActivityTaskTemplateCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.ActivityTaskTemplate> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileRequest", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects.FileProcessing")]
    [System.SerializableAttribute()]
    public partial class FileRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool _hasFileBeenReceivedField;
        
        private string _jobIDField;
        
        private string _sourceSystemField;
        
        private bool mblnIsEncryptedField;
        
        private int mintSizeInBytesField;
        
        private string mstrAssociationTypeField;
        
        private string mstrDescriptionField;
        
        private string mstrHashField;
        
        private string mstrLocalPathField;
        
        private string mstrPathField;
        
        private string mstrServerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _hasFileBeenReceived {
            get {
                return this._hasFileBeenReceivedField;
            }
            set {
                if ((this._hasFileBeenReceivedField.Equals(value) != true)) {
                    this._hasFileBeenReceivedField = value;
                    this.RaisePropertyChanged("_hasFileBeenReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _jobID {
            get {
                return this._jobIDField;
            }
            set {
                if ((object.ReferenceEquals(this._jobIDField, value) != true)) {
                    this._jobIDField = value;
                    this.RaisePropertyChanged("_jobID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _sourceSystem {
            get {
                return this._sourceSystemField;
            }
            set {
                if ((object.ReferenceEquals(this._sourceSystemField, value) != true)) {
                    this._sourceSystemField = value;
                    this.RaisePropertyChanged("_sourceSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool mblnIsEncrypted {
            get {
                return this.mblnIsEncryptedField;
            }
            set {
                if ((this.mblnIsEncryptedField.Equals(value) != true)) {
                    this.mblnIsEncryptedField = value;
                    this.RaisePropertyChanged("mblnIsEncrypted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int mintSizeInBytes {
            get {
                return this.mintSizeInBytesField;
            }
            set {
                if ((this.mintSizeInBytesField.Equals(value) != true)) {
                    this.mintSizeInBytesField = value;
                    this.RaisePropertyChanged("mintSizeInBytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mstrAssociationType {
            get {
                return this.mstrAssociationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.mstrAssociationTypeField, value) != true)) {
                    this.mstrAssociationTypeField = value;
                    this.RaisePropertyChanged("mstrAssociationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mstrDescription {
            get {
                return this.mstrDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.mstrDescriptionField, value) != true)) {
                    this.mstrDescriptionField = value;
                    this.RaisePropertyChanged("mstrDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mstrHash {
            get {
                return this.mstrHashField;
            }
            set {
                if ((object.ReferenceEquals(this.mstrHashField, value) != true)) {
                    this.mstrHashField = value;
                    this.RaisePropertyChanged("mstrHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mstrLocalPath {
            get {
                return this.mstrLocalPathField;
            }
            set {
                if ((object.ReferenceEquals(this.mstrLocalPathField, value) != true)) {
                    this.mstrLocalPathField = value;
                    this.RaisePropertyChanged("mstrLocalPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mstrPath {
            get {
                return this.mstrPathField;
            }
            set {
                if ((object.ReferenceEquals(this.mstrPathField, value) != true)) {
                    this.mstrPathField = value;
                    this.RaisePropertyChanged("mstrPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string mstrServer {
            get {
                return this.mstrServerField;
            }
            set {
                if ((object.ReferenceEquals(this.mstrServerField, value) != true)) {
                    this.mstrServerField = value;
                    this.RaisePropertyChanged("mstrServer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://FinalBuild.co.uk/LookupService", ConfigurationName="Services.ILookupService")]
    public interface ILookupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivityTree", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivityTreeResponse")]
        BusinessObjects.WorkManagement.ActivityTree GetActivityTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivityTreeFiltered", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivityTreeFilteredRespo" +
            "nse")]
        BusinessObjects.WorkManagement.ActivityTree GetActivityTreeFiltered(string topLevelCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivitiesForMobile", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivitiesForMobileRespon" +
            "se")]
        IntegrationWebSiteMvc.Services.ActivityCollection GetActivitiesForMobile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivitiesMatchingCriteri" +
            "a", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivitiesMatchingCriteri" +
            "aResponse")]
        IntegrationWebSiteMvc.Services.ActivityCollection GetActivitiesMatchingCriteria(string targetCategory, string targetRegion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/SaveActivity", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/SaveActivityResponse")]
        int SaveActivity(BusinessObjects.WorkManagement.Activity activity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetTaskLibrary", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetTaskLibraryResponse")]
        IntegrationWebSiteMvc.Services.ActivityTaskTemplateCollection GetTaskLibrary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetTaskLookupData", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetTaskLookupDataResponse")]
        BusinessObjects.WorkManagement.TaskLookupData GetTaskLookupData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetTaskLookupDataBySourceSys" +
            "tem", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetTaskLookupDataBySourceSys" +
            "temResponse")]
        BusinessObjects.WorkManagement.TaskLookupData GetTaskLookupDataBySourceSystem(string sourceSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetPriorityLookupData", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetPriorityLookupDataRespons" +
            "e")]
        BusinessObjects.WorkManagement.PriorityLookupData GetPriorityLookupData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetOnHoldLookupData", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetOnHoldLookupDataResponse")]
        IntegrationWebSiteMvc.Services.OnHoldReasonCollection GetOnHoldLookupData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivityLookupData", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivityLookupDataRespons" +
            "e")]
        System.Collections.Generic.List<string> GetActivityLookupData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivityOnHoldReasons", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetActivityOnHoldReasonsResp" +
            "onse")]
        IntegrationWebSiteMvc.Services.OnHoldReasonCollection GetActivityOnHoldReasons(int activityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/SaveTaskTemplate", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/SaveTaskTemplateResponse")]
        int SaveTaskTemplate(BusinessObjects.WorkManagement.ActivityTaskTemplate taskTemplate, int activityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/SaveTaskTemplateAndActivityS" +
            "equence", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/SaveTaskTemplateAndActivityS" +
            "equenceResponse")]
        int SaveTaskTemplateAndActivitySequence(BusinessObjects.WorkManagement.ActivityTaskTemplate taskTemplate, int activityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/SaveCategory", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/SaveCategoryResponse")]
        int SaveCategory(string categoryName, int parentCategoryID, int categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/SaveLookupData", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/SaveLookupDataResponse")]
        bool SaveLookupData(BusinessObjects.WorkManagement.TaskLookupData lookupData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/RequestLookupContainer", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/RequestLookupContainerRespon" +
            "se")]
        IntegrationWebSiteMvc.Services.FileRequest RequestLookupContainer(BusinessObjects.WorkManagement.eWMSourceSystem sourceSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/GetWorkflowLookupData", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/GetWorkflowLookupDataRespons" +
            "e")]
        IntegrationWebSiteMvc.Services.ReferenceTypeCollection GetWorkflowLookupData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/RemoveTasksFromActivity", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/RemoveTasksFromActivityRespo" +
            "nse")]
        bool RemoveTasksFromActivity(string strTasks, int intActivityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/AddTasksToActivity", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/AddTasksToActivityResponse")]
        bool AddTasksToActivity(string strTasks, int intActivityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/LookupService/ILookupService/SaveTaskSequence", ReplyAction="http://FinalBuild.co.uk/LookupService/ILookupService/SaveTaskSequenceResponse")]
        int SaveTaskSequence(BusinessObjects.WorkManagement.ActivityTaskTemplate taskTemplate, int activityID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILookupServiceChannel : IntegrationWebSiteMvc.Services.ILookupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LookupServiceClient : System.ServiceModel.ClientBase<IntegrationWebSiteMvc.Services.ILookupService>, IntegrationWebSiteMvc.Services.ILookupService {
        
        public LookupServiceClient() {
        }
        
        public LookupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LookupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LookupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusinessObjects.WorkManagement.ActivityTree GetActivityTree() {
            return base.Channel.GetActivityTree();
        }
        
        public BusinessObjects.WorkManagement.ActivityTree GetActivityTreeFiltered(string topLevelCategory) {
            return base.Channel.GetActivityTreeFiltered(topLevelCategory);
        }
        
        public IntegrationWebSiteMvc.Services.ActivityCollection GetActivitiesForMobile() {
            return base.Channel.GetActivitiesForMobile();
        }
        
        public IntegrationWebSiteMvc.Services.ActivityCollection GetActivitiesMatchingCriteria(string targetCategory, string targetRegion) {
            return base.Channel.GetActivitiesMatchingCriteria(targetCategory, targetRegion);
        }
        
        public int SaveActivity(BusinessObjects.WorkManagement.Activity activity) {
            return base.Channel.SaveActivity(activity);
        }
        
        public IntegrationWebSiteMvc.Services.ActivityTaskTemplateCollection GetTaskLibrary() {
            return base.Channel.GetTaskLibrary();
        }
        
        public BusinessObjects.WorkManagement.TaskLookupData GetTaskLookupData() {
            return base.Channel.GetTaskLookupData();
        }
        
        public BusinessObjects.WorkManagement.TaskLookupData GetTaskLookupDataBySourceSystem(string sourceSystem) {
            return base.Channel.GetTaskLookupDataBySourceSystem(sourceSystem);
        }
        
        public BusinessObjects.WorkManagement.PriorityLookupData GetPriorityLookupData() {
            return base.Channel.GetPriorityLookupData();
        }
        
        public IntegrationWebSiteMvc.Services.OnHoldReasonCollection GetOnHoldLookupData() {
            return base.Channel.GetOnHoldLookupData();
        }
        
        public System.Collections.Generic.List<string> GetActivityLookupData() {
            return base.Channel.GetActivityLookupData();
        }
        
        public IntegrationWebSiteMvc.Services.OnHoldReasonCollection GetActivityOnHoldReasons(int activityID) {
            return base.Channel.GetActivityOnHoldReasons(activityID);
        }
        
        public int SaveTaskTemplate(BusinessObjects.WorkManagement.ActivityTaskTemplate taskTemplate, int activityID) {
            return base.Channel.SaveTaskTemplate(taskTemplate, activityID);
        }
        
        public int SaveTaskTemplateAndActivitySequence(BusinessObjects.WorkManagement.ActivityTaskTemplate taskTemplate, int activityID) {
            return base.Channel.SaveTaskTemplateAndActivitySequence(taskTemplate, activityID);
        }
        
        public int SaveCategory(string categoryName, int parentCategoryID, int categoryID) {
            return base.Channel.SaveCategory(categoryName, parentCategoryID, categoryID);
        }
        
        public bool SaveLookupData(BusinessObjects.WorkManagement.TaskLookupData lookupData) {
            return base.Channel.SaveLookupData(lookupData);
        }
        
        public IntegrationWebSiteMvc.Services.FileRequest RequestLookupContainer(BusinessObjects.WorkManagement.eWMSourceSystem sourceSystem) {
            return base.Channel.RequestLookupContainer(sourceSystem);
        }
        
        public IntegrationWebSiteMvc.Services.ReferenceTypeCollection GetWorkflowLookupData() {
            return base.Channel.GetWorkflowLookupData();
        }
        
        public bool RemoveTasksFromActivity(string strTasks, int intActivityID) {
            return base.Channel.RemoveTasksFromActivity(strTasks, intActivityID);
        }
        
        public bool AddTasksToActivity(string strTasks, int intActivityID) {
            return base.Channel.AddTasksToActivity(strTasks, intActivityID);
        }
        
        public int SaveTaskSequence(BusinessObjects.WorkManagement.ActivityTaskTemplate taskTemplate, int activityID) {
            return base.Channel.SaveTaskSequence(taskTemplate, activityID);
        }
    }
}
