using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml;
using System.Xml.Serialization;
using BusinessObjects;


[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("urn:FinalBuild", ClrNamespace="FinalBuild")]


namespace FinalBuild
{


/// <summary>
/// BackgroundTaskSettings
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class BackgroundTaskSettings {
    
    #region Auto Generated Code
    /// <remarks/>
    private string mstrName;
    
    /// <remarks/>
    private string mstrDescription;
    
    /// <remarks/>
    private int mintPollingInterval;
    
    /// <remarks/>
    private int mintPollingWaitDuration;
    
    /// <summary>
    /// Name
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Name {
        get {
            return this.mstrName;
        }
        set {
            this.mstrName = value;
        }
    }
    
    /// <summary>
    /// Description
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Description {
        get {
            return this.mstrDescription;
        }
        set {
            this.mstrDescription = value;
        }
    }
    
    /// <summary>
    /// PollingInterval
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int PollingInterval {
        get {
            return this.mintPollingInterval;
        }
        set {
            this.mintPollingInterval = value;
        }
    }
    
    /// <summary>
    /// PollingWaitDuration
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int PollingWaitDuration {
        get {
            return this.mintPollingWaitDuration;
        }
        set {
            this.mintPollingWaitDuration = value;
        }
    }
    #endregion
}




/// <summary>
/// BackgroundTaskSettingsCollection
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.Runtime.Serialization.CollectionDataContractAttribute()]
public partial class BackgroundTaskSettingsCollection : System.ComponentModel.BindingList<BackgroundTaskSettings> {
}




/// <summary>
/// DeviceInfo
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class DeviceInfo {
    
    #region Auto Generated Code
    /// <remarks/>
    private eLoggingLevel mobjLoggingLevel;
    
    /// <remarks/>
    private int mintDownloadPollingInterval;
    
    /// <remarks/>
    private int mintMaxNoOfWorkItemsAllowed;
    
    /// <remarks/>
    private int mintCurrentNoOfWorkItemsPresent;
    
    /// <remarks/>
    private int mintDownloadPollingWaitDuration;
    
    /// <remarks/>
    private BackgroundTaskSettingsCollection mColBackgroundTasks;
    
    /// <remarks/>
    private int mintUploadBatchSize;
    
    /// <remarks/>
    private int mintMaxNoOfSubItemsAllowed;
    
    /// <remarks/>
    private int mintCurrentNoOfSubItemsPresent;
    
    /// <remarks/>
    private int mintMaxNoOfWorkItemsDisplayed;
    
    /// <remarks/>
    private bool mblnIsClientLockdownOn;
    
    /// <remarks/>
    private string mstrBusinessStream;
    
    /// <remarks/>
    private int mintPageSize;
    
    /// <remarks/>
    private string mstrSourceName;
    
    /// <remarks/>
    private bool mblnGroupPPM;
    
    /// <remarks/>
    private bool mblnApplyToHierarchy;
    
    public DeviceInfo() {
        this.IsClientLockdownOn = false;
    }
    
    /// <summary>
    /// LoggingLevel
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public eLoggingLevel LoggingLevel {
        get {
            return this.mobjLoggingLevel;
        }
        set {
            this.mobjLoggingLevel = value;
        }
    }
    
    /// <summary>
    /// DownloadPollingInterval
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int DownloadPollingInterval {
        get {
            return this.mintDownloadPollingInterval;
        }
        set {
            this.mintDownloadPollingInterval = value;
        }
    }
    
    /// <summary>
    /// For MeterReading this is NoOfJobs present (Ad Hoc)
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int MaxNoOfWorkItemsAllowed {
        get {
            return this.mintMaxNoOfWorkItemsAllowed;
        }
        set {
            this.mintMaxNoOfWorkItemsAllowed = value;
        }
    }
    
    /// <summary>
    /// CurrentNoOfWorkItemsPresent
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int CurrentNoOfWorkItemsPresent {
        get {
            return this.mintCurrentNoOfWorkItemsPresent;
        }
        set {
            this.mintCurrentNoOfWorkItemsPresent = value;
        }
    }
    
    /// <summary>
    /// DownloadPollingWaitDuration
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int DownloadPollingWaitDuration {
        get {
            return this.mintDownloadPollingWaitDuration;
        }
        set {
            this.mintDownloadPollingWaitDuration = value;
        }
    }
    
    /// <summary>
    /// BackgroundTasks
    /// </summary>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public BackgroundTaskSettingsCollection BackgroundTasks {
        get {
            return this.mColBackgroundTasks;
        }
        set {
            this.mColBackgroundTasks = value;
        }
    }
    
    /// <summary>
    /// UploadBatchSize
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int UploadBatchSize {
        get {
            return this.mintUploadBatchSize;
        }
        set {
            this.mintUploadBatchSize = value;
        }
    }
    
    /// <summary>
    /// For MeterReading this is NoOfMeters present (Cyclic or Mini Round batch)
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int MaxNoOfSubItemsAllowed {
        get {
            return this.mintMaxNoOfSubItemsAllowed;
        }
        set {
            this.mintMaxNoOfSubItemsAllowed = value;
        }
    }
    
    /// <summary>
    /// CurrentNoOfSubItemsPresent
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int CurrentNoOfSubItemsPresent {
        get {
            return this.mintCurrentNoOfSubItemsPresent;
        }
        set {
            this.mintCurrentNoOfSubItemsPresent = value;
        }
    }
    
    /// <summary>
    /// MaxNoOfWorkItemsDisplayed
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int MaxNoOfWorkItemsDisplayed {
        get {
            return this.mintMaxNoOfWorkItemsDisplayed;
        }
        set {
            this.mintMaxNoOfWorkItemsDisplayed = value;
        }
    }
    
    /// <summary>
    /// This flag denotes whether to restrict what Jobs the Mobile user can start. Logic to utilise this flag be interact with Stream (Region)
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsClientLockdownOn {
        get {
            return this.mblnIsClientLockdownOn;
        }
        set {
            this.mblnIsClientLockdownOn = value;
        }
    }
    
    /// <summary>
    /// This is the Stream (Region) associated with the Mobile user
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string BusinessStream {
        get {
            return this.mstrBusinessStream;
        }
        set {
            this.mstrBusinessStream = value;
        }
    }
    
    /// <summary>
    /// Maximum number of records to display on the client per container ie. DataGrid
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int PageSize {
        get {
            return this.mintPageSize;
        }
        set {
            this.mintPageSize = value;
        }
    }
    
    /// <summary>
    /// SourceName
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string SourceName {
        get {
            return this.mstrSourceName;
        }
        set {
            this.mstrSourceName = value;
        }
    }
    
    /// <summary>
    /// GroupPPM
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool GroupPPM {
        get {
            return this.mblnGroupPPM;
        }
        set {
            this.mblnGroupPPM = value;
        }
    }
    
    /// <summary>
    /// This flag denotes whether to hierarchically apply Device Info values to those groups (Regions/Users) within a particular Stream
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool ApplyToHierarchy {
        get {
            return this.mblnApplyToHierarchy;
        }
        set {
            this.mblnApplyToHierarchy = value;
        }
    }
    #endregion
}




/// <summary>
/// eLoggingLevel
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild")]
[System.Runtime.Serialization.DataContractAttribute()]
public enum eLoggingLevel {
    
    /// <summary>
    /// Most detailed level of logging
    /// </summary>
    [System.Runtime.Serialization.EnumMemberAttribute()]
    Verbose,
    
    /// <summary>
    /// Only sends logged Exceptions back
    /// </summary>
    [System.Runtime.Serialization.EnumMemberAttribute()]
    ExceptionsOnly,
    
    /// <summary>
    /// No Client Side log entries
    /// </summary>
    [System.Runtime.Serialization.EnumMemberAttribute()]
    None,
}




/// <summary>
/// eWorkDownloadedAction
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild")]
[System.Runtime.Serialization.DataContractAttribute()]
public enum eWorkDownloadedAction {
    
    /// <summary>
    /// Add downloaded items into local data
    /// </summary>
    [System.Runtime.Serialization.EnumMemberAttribute()]
    Added,
    
    /// <summary>
    /// Remove downloaded items from local data
    /// </summary>
    [System.Runtime.Serialization.EnumMemberAttribute()]
    Removed,
    
    /// <summary>
    /// Modify existing copies of downloaded items within local data
    /// </summary>
    [System.Runtime.Serialization.EnumMemberAttribute()]
    Modified,
}




/// <summary>
/// ServerFeedback
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild", IsNullable=false)]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ServerFeedback {
    
    #region Auto Generated Code
    /// <remarks/>
    private DeviceInfo mobjDeviceSettings;
    
    /// <remarks/>
    private System.DateTime mdteServerTime;
    
    /// <remarks/>
    private System.DateTime mdteLastDownloadDate;
    
    /// <remarks/>
    private System.DateTime mdteLastUploadDate;
    
    /// <remarks/>
    private ThrottlingParametersCollection mColThrottlingSettings;
    
    /// <remarks/>
    private SupportingDataStatisticsCollection mColSupportingDataSettings;
    
    /// <summary>
    /// DeviceSettings
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public DeviceInfo DeviceSettings {
        get {
            return this.mobjDeviceSettings;
        }
        set {
            this.mobjDeviceSettings = value;
        }
    }
    
    /// <summary>
    /// ServerTime
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ServerTime {
        get {
            return this.mdteServerTime;
        }
        set {
            this.mdteServerTime = value;
        }
    }
    
    /// <summary>
    /// LastDownloadDate
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime LastDownloadDate {
        get {
            return this.mdteLastDownloadDate;
        }
        set {
            this.mdteLastDownloadDate = value;
        }
    }
    
    /// <summary>
    /// LastUploadDate
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime LastUploadDate {
        get {
            return this.mdteLastUploadDate;
        }
        set {
            this.mdteLastUploadDate = value;
        }
    }
    
    /// <summary>
    /// ThrottlingSettings
    /// </summary>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public ThrottlingParametersCollection ThrottlingSettings {
        get {
            return this.mColThrottlingSettings;
        }
        set {
            this.mColThrottlingSettings = value;
        }
    }
    
    /// <summary>
    /// SupportingDataSettings
    /// </summary>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public SupportingDataStatisticsCollection SupportingDataSettings {
        get {
            return this.mColSupportingDataSettings;
        }
        set {
            this.mColSupportingDataSettings = value;
        }
    }
    #endregion
}




/// <summary>
/// SupportingDataStatistics
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class SupportingDataStatistics {
    
    #region Auto Generated Code
    /// <remarks/>
    private string mstrBusinessStream;
    
    /// <remarks/>
    private System.DateTime mdteLastUpdatedDate;
    
    /// <summary>
    /// BusinessStream
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string BusinessStream {
        get {
            return this.mstrBusinessStream;
        }
        set {
            this.mstrBusinessStream = value;
        }
    }
    
    /// <summary>
    /// LastUpdatedDate
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime LastUpdatedDate {
        get {
            return this.mdteLastUpdatedDate;
        }
        set {
            this.mdteLastUpdatedDate = value;
        }
    }
    #endregion
}




/// <summary>
/// SupportingDataStatisticsCollection
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.Runtime.Serialization.CollectionDataContractAttribute()]
public partial class SupportingDataStatisticsCollection : System.ComponentModel.BindingList<SupportingDataStatistics> {
}




/// <summary>
/// ThrottlingParameters
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class ThrottlingParameters {
    
    #region Auto Generated Code
    /// <remarks/>
    private string mstrBusinessStream;
    
    /// <remarks/>
    private int mintMaxNoOfWorkItemsPerDownload;
    
    /// <remarks/>
    private int mintCutoffDays;
    
    /// <remarks/>
    private bool mblnCutoffToCalendarDay;
    
    /// <remarks/>
    private int mintCutoffHours;
    
    /// <remarks/>
    private string mstrSourceName;
    
    /// <remarks/>
    private bool mblnThrottleChildren;
    
    /// <remarks/>
    private bool mblnOutOfHours;
    
    /// <remarks/>
    private bool mblnGroupPPM;
    
    /// <remarks/>
    private string mstrModifiedBy;
    
    /// <remarks/>
    private System.DateTime mdteModifiedDate;
    
    /// <remarks/>
    private string mstrComments;
    
    /// <summary>
    /// BusinessStream
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string BusinessStream {
        get {
            return this.mstrBusinessStream;
        }
        set {
            this.mstrBusinessStream = value;
        }
    }
    
    /// <summary>
    /// MaxNoOfWorkItemsPerDownload
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int MaxNoOfWorkItemsPerDownload {
        get {
            return this.mintMaxNoOfWorkItemsPerDownload;
        }
        set {
            this.mintMaxNoOfWorkItemsPerDownload = value;
        }
    }
    
    /// <summary>
    /// CutoffDays
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int CutoffDays {
        get {
            return this.mintCutoffDays;
        }
        set {
            this.mintCutoffDays = value;
        }
    }
    
    /// <summary>
    /// CutoffToCalendarDay
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool CutoffToCalendarDay {
        get {
            return this.mblnCutoffToCalendarDay;
        }
        set {
            this.mblnCutoffToCalendarDay = value;
        }
    }
    
    /// <summary>
    /// CutoffHours
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int CutoffHours {
        get {
            return this.mintCutoffHours;
        }
        set {
            this.mintCutoffHours = value;
        }
    }
    
    /// <summary>
    /// SourceName
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string SourceName {
        get {
            return this.mstrSourceName;
        }
        set {
            this.mstrSourceName = value;
        }
    }
    
    /// <summary>
    /// ThrottleChildren
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool ThrottleChildren {
        get {
            return this.mblnThrottleChildren;
        }
        set {
            this.mblnThrottleChildren = value;
        }
    }
    
    /// <summary>
    /// OutOfHours
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool OutOfHours {
        get {
            return this.mblnOutOfHours;
        }
        set {
            this.mblnOutOfHours = value;
        }
    }
    
    /// <summary>
    /// GroupPPM
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool GroupPPM {
        get {
            return this.mblnGroupPPM;
        }
        set {
            this.mblnGroupPPM = value;
        }
    }
    
    /// <summary>
    /// ModifiedBy
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string ModifiedBy {
        get {
            return this.mstrModifiedBy;
        }
        set {
            this.mstrModifiedBy = value;
        }
    }
    
    /// <summary>
    /// ModifiedDate
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime ModifiedDate {
        get {
            return this.mdteModifiedDate;
        }
        set {
            this.mdteModifiedDate = value;
        }
    }
    
    /// <summary>
    /// Comments
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Comments {
        get {
            return this.mstrComments;
        }
        set {
            this.mstrComments = value;
        }
    }
    #endregion
}




/// <summary>
/// ThrottlingParametersCollection
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.Runtime.Serialization.CollectionDataContractAttribute()]
public partial class ThrottlingParametersCollection : System.ComponentModel.BindingList<ThrottlingParameters> {
}




/// <summary>
/// UserMessage
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class UserMessage {
    
    #region Auto Generated Code
    /// <remarks/>
    private int mintID;
    
    /// <remarks/>
    private string mstrRecipient;
    
    /// <remarks/>
    private System.DateTime mdteDateCreated;
    
    /// <remarks/>
    private string mstrBody;
    
    /// <remarks/>
    private System.DateTime mdteDateReceived;
    
    /// <remarks/>
    private string mstrSubject;
    
    /// <remarks/>
    private string mstrSender;
    
    /// <remarks/>
    private string mstrTargetUrl;
    
    /// <remarks/>
    private int mintExpiryMinutesAfterSent;
    
    /// <remarks/>
    private int mintExpiryMinutesAfterCreation;
    
    /// <remarks/>
    private System.DateTime mdteDateExpired;
    
    /// <remarks/>
    private int mintPriorityLevel;
    
    /// <remarks/>
    private int mintAlertID;
    
    public UserMessage() {
        this.ExpiryMinutesAfterSent = -1;
        this.ExpiryMinutesAfterCreation = -1;
    }
    
    /// <summary>
    /// ID
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ID {
        get {
            return this.mintID;
        }
        set {
            this.mintID = value;
        }
    }
    
    /// <summary>
    /// Recipient
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Recipient {
        get {
            return this.mstrRecipient;
        }
        set {
            this.mstrRecipient = value;
        }
    }
    
    /// <summary>
    /// DateCreated
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime DateCreated {
        get {
            return this.mdteDateCreated;
        }
        set {
            this.mdteDateCreated = value;
        }
    }
    
    /// <summary>
    /// Body
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Body {
        get {
            return this.mstrBody;
        }
        set {
            this.mstrBody = value;
        }
    }
    
    /// <summary>
    /// DateReceived
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime DateReceived {
        get {
            return this.mdteDateReceived;
        }
        set {
            this.mdteDateReceived = value;
        }
    }
    
    /// <summary>
    /// Subject
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Subject {
        get {
            return this.mstrSubject;
        }
        set {
            this.mstrSubject = value;
        }
    }
    
    /// <summary>
    /// Sender
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string Sender {
        get {
            return this.mstrSender;
        }
        set {
            this.mstrSender = value;
        }
    }
    
    /// <summary>
    /// TargetUrl
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string TargetUrl {
        get {
            return this.mstrTargetUrl;
        }
        set {
            this.mstrTargetUrl = value;
        }
    }
    
    /// <summary>
    /// No.of Minutes after Alert is sent to Expire it
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ExpiryMinutesAfterSent {
        get {
            return this.mintExpiryMinutesAfterSent;
        }
        set {
            this.mintExpiryMinutesAfterSent = value;
        }
    }
    
    /// <summary>
    /// No.of Minutes after Alert is created to Expire it
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ExpiryMinutesAfterCreation {
        get {
            return this.mintExpiryMinutesAfterCreation;
        }
        set {
            this.mintExpiryMinutesAfterCreation = value;
        }
    }
    
    /// <summary>
    /// Datetime the message was Expired if indeed it was
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime DateExpired {
        get {
            return this.mdteDateExpired;
        }
        set {
            this.mdteDateExpired = value;
        }
    }
    
    /// <summary>
    /// Allows a Priority to be associated e.g Alert System property EscalationLevel
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int PriorityLevel {
        get {
            return this.mintPriorityLevel;
        }
        set {
            this.mintPriorityLevel = value;
        }
    }
    
    /// <summary>
    /// The ID of the associated Alert
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int AlertID {
        get {
            return this.mintAlertID;
        }
        set {
            this.mintAlertID = value;
        }
    }
    #endregion
}




/// <summary>
/// UserMessageCollection
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.Runtime.Serialization.CollectionDataContractAttribute()]
public partial class UserMessageCollection : System.ComponentModel.BindingList<UserMessage> {
}




/// <summary>
/// WorkReceivedAcknowledgement
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkReceivedComplexAcknowledgement))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class WorkReceivedAcknowledgement {
    
    #region Auto Generated Code
    /// <remarks/>
    private int mintEntityID;
    
    /// <remarks/>
    private string mstrEntityType;
    
    /// <remarks/>
    private eWorkDownloadedAction mobjActionTaken;
    
    /// <remarks/>
    private string mstrUserID;
    
    /// <remarks/>
    private System.DateTime mdteDateReceived;
    
    /// <remarks/>
    private string mstrDeviceID;
    
    /// <summary>
    /// EntityID
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int EntityID {
        get {
            return this.mintEntityID;
        }
        set {
            this.mintEntityID = value;
        }
    }
    
    /// <summary>
    /// EntityType
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string EntityType {
        get {
            return this.mstrEntityType;
        }
        set {
            this.mstrEntityType = value;
        }
    }
    
    /// <summary>
    /// ActionTaken
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public eWorkDownloadedAction ActionTaken {
        get {
            return this.mobjActionTaken;
        }
        set {
            this.mobjActionTaken = value;
        }
    }
    
    /// <summary>
    /// UserID
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string UserID {
        get {
            return this.mstrUserID;
        }
        set {
            this.mstrUserID = value;
        }
    }
    
    /// <summary>
    /// DateReceived
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime DateReceived {
        get {
            return this.mdteDateReceived;
        }
        set {
            this.mdteDateReceived = value;
        }
    }
    
    /// <summary>
    /// DeviceID
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public string DeviceID {
        get {
            return this.mstrDeviceID;
        }
        set {
            this.mstrDeviceID = value;
        }
    }
    #endregion
}




/// <summary>
/// WorkReceivedAcknowledgementCollection
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.Runtime.Serialization.CollectionDataContractAttribute()]
public partial class WorkReceivedAcknowledgementCollection : System.ComponentModel.BindingList<WorkReceivedAcknowledgement> {
}




/// <summary>
/// WorkReceivedComplexAcknowledgement
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class WorkReceivedComplexAcknowledgement : WorkReceivedAcknowledgement {
    
    #region Auto Generated Code
    /// <remarks/>
    private WorkReceivedAcknowledgementCollection mColChildren;
    
    /// <remarks/>
    private bool mblnIsSupportingData;
    
    /// <remarks/>
    private System.DateTime mdteSupportingDataChangeDate;
    
    public WorkReceivedComplexAcknowledgement() {
        this.IsSupportingData = false;
    }
    
    /// <summary>
    /// Children
    /// </summary>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    [System.Runtime.Serialization.DataMemberAttribute()]
    public WorkReceivedAcknowledgementCollection Children {
        get {
            return this.mColChildren;
        }
        set {
            this.mColChildren = value;
        }
    }
    
    /// <summary>
    /// Flag denoting that the Acknowledgment is for Supporting Data received.
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsSupportingData {
        get {
            return this.mblnIsSupportingData;
        }
        set {
            this.mblnIsSupportingData = value;
        }
    }
    
    /// <summary>
    /// The date on which the Assignment Supporting Data, that triggered the acknowledgment, was changed.
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime SupportingDataChangeDate {
        get {
            return this.mdteSupportingDataChangeDate;
        }
        set {
            this.mdteSupportingDataChangeDate = value;
        }
    }
    #endregion
}




/// <summary>
/// WorkReceivedComplexAcknowledgementCollection
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.Runtime.Serialization.CollectionDataContractAttribute()]
public partial class WorkReceivedComplexAcknowledgementCollection : System.ComponentModel.BindingList<WorkReceivedComplexAcknowledgement> {
}




/// <summary>
/// WorkStatusInfo
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FinalBuild.co.uk/FinalBuild")]
[System.Runtime.Serialization.DataContractAttribute()]
public partial class WorkStatusInfo {
    
    #region Auto Generated Code
    /// <remarks/>
    private int mintID;
    
    /// <remarks/>
    private bool mblnIsWorkPackageComplete;
    
    /// <remarks/>
    private int mintNoOfWorkItemsDownloaded;
    
    /// <remarks/>
    private int mintNoOfWorkItemsUploaded;
    
    /// <remarks/>
    private int mintWorkItemsToDo;
    
    /// <remarks/>
    private int mintWorkItemsAttempted;
    
    /// <remarks/>
    private int mintWorkItemsDone;
    
    /// <remarks/>
    private int mintHighPriorityWorkItemsToDo;
    
    /// <remarks/>
    private int mintHighPriorityWorkItemsAttempted;
    
    /// <remarks/>
    private int mintHighPriorityWorkItemsDone;
    
    /// <remarks/>
    private System.DateTime mdteLastWorkItemCompletedDate;
    
    /// <remarks/>
    private int mintLatestBatchNo;
    
    /// <summary>
    /// ID
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int ID {
        get {
            return this.mintID;
        }
        set {
            this.mintID = value;
        }
    }
    
    /// <summary>
    /// IsWorkPackageComplete
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public bool IsWorkPackageComplete {
        get {
            return this.mblnIsWorkPackageComplete;
        }
        set {
            this.mblnIsWorkPackageComplete = value;
        }
    }
    
    /// <summary>
    /// NoOfWorkItemsDownloaded
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int NoOfWorkItemsDownloaded {
        get {
            return this.mintNoOfWorkItemsDownloaded;
        }
        set {
            this.mintNoOfWorkItemsDownloaded = value;
        }
    }
    
    /// <summary>
    /// NoOfWorkItemsUploaded
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int NoOfWorkItemsUploaded {
        get {
            return this.mintNoOfWorkItemsUploaded;
        }
        set {
            this.mintNoOfWorkItemsUploaded = value;
        }
    }
    
    /// <summary>
    /// WorkItemsToDo
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int WorkItemsToDo {
        get {
            return this.mintWorkItemsToDo;
        }
        set {
            this.mintWorkItemsToDo = value;
        }
    }
    
    /// <summary>
    /// WorkItemsAttempted
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int WorkItemsAttempted {
        get {
            return this.mintWorkItemsAttempted;
        }
        set {
            this.mintWorkItemsAttempted = value;
        }
    }
    
    /// <summary>
    /// WorkItemsDone
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int WorkItemsDone {
        get {
            return this.mintWorkItemsDone;
        }
        set {
            this.mintWorkItemsDone = value;
        }
    }
    
    /// <summary>
    /// HighPriorityWorkItemsToDo
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int HighPriorityWorkItemsToDo {
        get {
            return this.mintHighPriorityWorkItemsToDo;
        }
        set {
            this.mintHighPriorityWorkItemsToDo = value;
        }
    }
    
    /// <summary>
    /// HighPriorityWorkItemsAttempted
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int HighPriorityWorkItemsAttempted {
        get {
            return this.mintHighPriorityWorkItemsAttempted;
        }
        set {
            this.mintHighPriorityWorkItemsAttempted = value;
        }
    }
    
    /// <summary>
    /// HighPriorityWorkItemsDone
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int HighPriorityWorkItemsDone {
        get {
            return this.mintHighPriorityWorkItemsDone;
        }
        set {
            this.mintHighPriorityWorkItemsDone = value;
        }
    }
    
    /// <summary>
    /// LastWorkItemCompletedDate
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public System.DateTime LastWorkItemCompletedDate {
        get {
            return this.mdteLastWorkItemCompletedDate;
        }
        set {
            this.mdteLastWorkItemCompletedDate = value;
        }
    }
    
    /// <summary>
    /// LatestBatchNo
    /// </summary>
    [System.Runtime.Serialization.DataMemberAttribute()]
    public int LatestBatchNo {
        get {
            return this.mintLatestBatchNo;
        }
        set {
            this.mintLatestBatchNo = value;
        }
    }
    #endregion
}




/// <summary>
/// WorkStatusInfoCollection
/// </summary>
// This Class was generated by the VS2005CodeGenerator from an initial XSD
// Date Generated : 19/11/2013 16:45:22
// Author : FINALBUILD\apowell
// 
[System.Runtime.Serialization.CollectionDataContractAttribute()]
public partial class WorkStatusInfoCollection : System.ComponentModel.BindingList<WorkStatusInfo> {
}


}
