//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationWebSiteMvc.CorporateData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReferenceTypeCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="ReferenceType")]
    [System.SerializableAttribute()]
    public class ReferenceTypeCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.ReferenceType> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects.AssetManagement")]
    [System.SerializableAttribute()]
    public partial class AssetSearchCriteria : BusinessObjects.WorkManagement.ReferenceType, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeOrDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeAttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeMeasurementHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentCodeOrDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntegrationWebSiteMvc.CorporateData.eAssetSearchType ParentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntegrationWebSiteMvc.CorporateData.eAssetSearchType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeOrDescription {
            get {
                return this.CodeOrDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeOrDescriptionField, value) != true)) {
                    this.CodeOrDescriptionField = value;
                    this.RaisePropertyChanged("CodeOrDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeAttributes {
            get {
                return this.IncludeAttributesField;
            }
            set {
                if ((this.IncludeAttributesField.Equals(value) != true)) {
                    this.IncludeAttributesField = value;
                    this.RaisePropertyChanged("IncludeAttributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeLocation {
            get {
                return this.IncludeLocationField;
            }
            set {
                if ((this.IncludeLocationField.Equals(value) != true)) {
                    this.IncludeLocationField = value;
                    this.RaisePropertyChanged("IncludeLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeMeasurementHistory {
            get {
                return this.IncludeMeasurementHistoryField;
            }
            set {
                if ((this.IncludeMeasurementHistoryField.Equals(value) != true)) {
                    this.IncludeMeasurementHistoryField = value;
                    this.RaisePropertyChanged("IncludeMeasurementHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentCodeOrDescription {
            get {
                return this.ParentCodeOrDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentCodeOrDescriptionField, value) != true)) {
                    this.ParentCodeOrDescriptionField = value;
                    this.RaisePropertyChanged("ParentCodeOrDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntegrationWebSiteMvc.CorporateData.eAssetSearchType ParentType {
            get {
                return this.ParentTypeField;
            }
            set {
                if ((this.ParentTypeField.Equals(value) != true)) {
                    this.ParentTypeField = value;
                    this.RaisePropertyChanged("ParentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntegrationWebSiteMvc.CorporateData.eAssetSearchType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eAssetSearchType", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects.AssetManagement")]
    public enum eAssetSearchType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Site = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Process = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Asset = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AssetAttributeCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="AssetAttribute")]
    [System.SerializableAttribute()]
    public class AssetAttributeCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.AssetAttribute> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CommentAuditRecordCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="CommentAuditRecord")]
    [System.SerializableAttribute()]
    public class CommentAuditRecordCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.CommentAuditRecord> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ContactCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="Contact")]
    [System.SerializableAttribute()]
    public class ContactCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.Contact> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AssetGroupCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="AssetGroup")]
    [System.SerializableAttribute()]
    public class AssetGroupCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.AssetGroup> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AssetCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="Asset")]
    [System.SerializableAttribute()]
    public class AssetCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.Asset> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PerformanceIndicatorGroupCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="PerformanceIndicatorGroup")]
    [System.SerializableAttribute()]
    public class PerformanceIndicatorGroupCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.PerformanceIndicatorGroup> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PerformanceIndicatorCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="PerformanceIndicator")]
    [System.SerializableAttribute()]
    public class PerformanceIndicatorCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.PerformanceIndicator> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PerformanceMeasurementCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="PerformanceMeasurement")]
    [System.SerializableAttribute()]
    public class PerformanceMeasurementCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.PerformanceMeasurement> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="MaterialCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="Material")]
    [System.SerializableAttribute()]
    public class MaterialCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.Material> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ResourceProfileCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="ResourceProfile")]
    [System.SerializableAttribute()]
    public class ResourceProfileCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.ResourceProfile> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SkillCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="Skill")]
    [System.SerializableAttribute()]
    public class SkillCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.Skill> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetUpdate", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects.AssetManagement")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IntegrationWebSiteMvc.CorporateData.AssetSearchCriteria))]
    public partial class AssetUpdate : BusinessObjects.Base, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssetIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntegrationWebSiteMvc.CorporateData.AssetAttributeCollection AttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BusinessObjects.WorkManagement.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasLocationChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BusinessObjects.WorkManagement.Location LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BusinessObjects.WorkManagement.ReferenceType ParentAssetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssetID {
            get {
                return this.AssetIDField;
            }
            set {
                if ((this.AssetIDField.Equals(value) != true)) {
                    this.AssetIDField = value;
                    this.RaisePropertyChanged("AssetID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetType {
            get {
                return this.AssetTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetTypeField, value) != true)) {
                    this.AssetTypeField = value;
                    this.RaisePropertyChanged("AssetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntegrationWebSiteMvc.CorporateData.AssetAttributeCollection Attributes {
            get {
                return this.AttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributesField, value) != true)) {
                    this.AttributesField = value;
                    this.RaisePropertyChanged("Attributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BusinessObjects.WorkManagement.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasLocationChanged {
            get {
                return this.HasLocationChangedField;
            }
            set {
                if ((this.HasLocationChangedField.Equals(value) != true)) {
                    this.HasLocationChangedField = value;
                    this.RaisePropertyChanged("HasLocationChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BusinessObjects.WorkManagement.Location Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BusinessObjects.WorkManagement.ReferenceType ParentAsset {
            get {
                return this.ParentAssetField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentAssetField, value) != true)) {
                    this.ParentAssetField = value;
                    this.RaisePropertyChanged("ParentAsset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StockItemCollection", Namespace="urn:BusinessObjects.WorkManagement", ItemName="StockItem")]
    [System.SerializableAttribute()]
    public class StockItemCollection : System.Collections.Generic.List<BusinessObjects.WorkManagement.StockItem> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerSearchCriteria", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CustomerSearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntegrationWebSiteMvc.CorporateData.eCustomerSearchType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntegrationWebSiteMvc.CorporateData.eCustomerSearchType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eCustomerSearchType", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum eCustomerSearchType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Client = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customer = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://FinalBuild.co.uk/ExternalDataService", ConfigurationName="CorporateData.IExternalDataService")]
    public interface IExternalDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SearchStock", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SearchStockRespo" +
            "nse")]
        System.Collections.Generic.List<BusinessObjects.WorkManagement.Stock> SearchStock(string materialSearchCriteria, int materialID, int jobID, string locationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/DeleteStockItems" +
            "ByMaterialAndJob", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/DeleteStockItems" +
            "ByMaterialAndJobResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IntegrationWebSiteMvc.CorporateData.AssetSearchCriteria))]
        bool DeleteStockItemsByMaterialAndJob(BusinessObjects.WorkManagement.StockItem stockItem, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/UpdateStockItems" +
            "ByMaterialAndJob", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/UpdateStockItems" +
            "ByMaterialAndJobResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IntegrationWebSiteMvc.CorporateData.AssetSearchCriteria))]
        bool UpdateStockItemsByMaterialAndJob(BusinessObjects.WorkManagement.StockItem stockItem, string location, int quantity, bool clearJob);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SearchAssets", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SearchAssetsResp" +
            "onse")]
        System.Collections.Generic.List<BusinessObjects.WorkManagement.Asset> SearchAssets(IntegrationWebSiteMvc.CorporateData.AssetSearchCriteria searchCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SearchCustomers", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SearchCustomersR" +
            "esponse")]
        System.Collections.Generic.List<BusinessObjects.WorkManagement.Customer> SearchCustomers(IntegrationWebSiteMvc.CorporateData.CustomerSearchCriteria searchCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SearchMaterials", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SearchMaterialsR" +
            "esponse")]
        System.Collections.Generic.List<BusinessObjects.WorkManagement.Material> SearchMaterials(string searchCriteria, int id, string manufacturer, string code, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SearchMeasuremen" +
            "ts", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SearchMeasuremen" +
            "tsResponse")]
        System.Collections.Generic.List<BusinessObjects.WorkManagement.PerformanceMeasurement> SearchMeasurements(string searchCriteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/EvolveMetadata", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/EvolveMetadataRe" +
            "sponse")]
        void EvolveMetadata(System.Collections.Generic.List<BusinessObjects.WorkManagement.Material> materials, System.Collections.Generic.List<BusinessObjects.WorkManagement.PerformanceMeasurement> measurements, System.Collections.Generic.List<BusinessObjects.WorkManagement.ActivityTask> tasks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/UploadAssetData", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/UploadAssetDataR" +
            "esponse")]
        IntegrationWebSiteMvc.CorporateData.AssetCollection UploadAssetData(IntegrationWebSiteMvc.CorporateData.AssetUpdate assetUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/UploadAssetMeasu" +
            "rements", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/UploadAssetMeasu" +
            "rementsResponse")]
        int UploadAssetMeasurements(int assetID, IntegrationWebSiteMvc.CorporateData.PerformanceMeasurementCollection measurements);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/UploadCustomerDa" +
            "ta", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/UploadCustomerDa" +
            "taResponse")]
        System.Collections.Generic.List<int> UploadCustomerData(BusinessObjects.WorkManagement.Customer customer, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SaveContactInfo", ReplyAction="http://FinalBuild.co.uk/ExternalDataService/IExternalDataService/SaveContactInfoR" +
            "esponse")]
        int SaveContactInfo(int parentEntityID, string parentEntityType, System.Collections.Generic.List<BusinessObjects.WorkManagement.Contact> contacts);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExternalDataServiceChannel : IntegrationWebSiteMvc.CorporateData.IExternalDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExternalDataServiceClient : System.ServiceModel.ClientBase<IntegrationWebSiteMvc.CorporateData.IExternalDataService>, IntegrationWebSiteMvc.CorporateData.IExternalDataService {
        
        public ExternalDataServiceClient() {
        }
        
        public ExternalDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExternalDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<BusinessObjects.WorkManagement.Stock> SearchStock(string materialSearchCriteria, int materialID, int jobID, string locationCode) {
            return base.Channel.SearchStock(materialSearchCriteria, materialID, jobID, locationCode);
        }
        
        public bool DeleteStockItemsByMaterialAndJob(BusinessObjects.WorkManagement.StockItem stockItem, int quantity) {
            return base.Channel.DeleteStockItemsByMaterialAndJob(stockItem, quantity);
        }
        
        public bool UpdateStockItemsByMaterialAndJob(BusinessObjects.WorkManagement.StockItem stockItem, string location, int quantity, bool clearJob) {
            return base.Channel.UpdateStockItemsByMaterialAndJob(stockItem, location, quantity, clearJob);
        }
        
        public System.Collections.Generic.List<BusinessObjects.WorkManagement.Asset> SearchAssets(IntegrationWebSiteMvc.CorporateData.AssetSearchCriteria searchCriteria) {
            return base.Channel.SearchAssets(searchCriteria);
        }
        
        public System.Collections.Generic.List<BusinessObjects.WorkManagement.Customer> SearchCustomers(IntegrationWebSiteMvc.CorporateData.CustomerSearchCriteria searchCriteria) {
            return base.Channel.SearchCustomers(searchCriteria);
        }
        
        public System.Collections.Generic.List<BusinessObjects.WorkManagement.Material> SearchMaterials(string searchCriteria, int id, string manufacturer, string code, string description) {
            return base.Channel.SearchMaterials(searchCriteria, id, manufacturer, code, description);
        }
        
        public System.Collections.Generic.List<BusinessObjects.WorkManagement.PerformanceMeasurement> SearchMeasurements(string searchCriteria) {
            return base.Channel.SearchMeasurements(searchCriteria);
        }
        
        public void EvolveMetadata(System.Collections.Generic.List<BusinessObjects.WorkManagement.Material> materials, System.Collections.Generic.List<BusinessObjects.WorkManagement.PerformanceMeasurement> measurements, System.Collections.Generic.List<BusinessObjects.WorkManagement.ActivityTask> tasks) {
            base.Channel.EvolveMetadata(materials, measurements, tasks);
        }
        
        public IntegrationWebSiteMvc.CorporateData.AssetCollection UploadAssetData(IntegrationWebSiteMvc.CorporateData.AssetUpdate assetUpdate) {
            return base.Channel.UploadAssetData(assetUpdate);
        }
        
        public int UploadAssetMeasurements(int assetID, IntegrationWebSiteMvc.CorporateData.PerformanceMeasurementCollection measurements) {
            return base.Channel.UploadAssetMeasurements(assetID, measurements);
        }
        
        public System.Collections.Generic.List<int> UploadCustomerData(BusinessObjects.WorkManagement.Customer customer, string userID) {
            return base.Channel.UploadCustomerData(customer, userID);
        }
        
        public int SaveContactInfo(int parentEntityID, string parentEntityType, System.Collections.Generic.List<BusinessObjects.WorkManagement.Contact> contacts) {
            return base.Channel.SaveContactInfo(parentEntityID, parentEntityType, contacts);
        }
    }
}
